---
- hosts: all

  tasks:
    - name: Checkout PiHole repo
      git:
        repo: 'https://github.com/pi-hole/pi-hole.git'
        dest: ~/repositories/pihole
        single_branch: true
        version: master
        depth: 1

    - name: Execute install script
      shell: 'basic-install.sh'
      args:
        chdir: '~/repositories/pihole/automated install'
      become: true
