---
- hosts: all

  vars:
    pihole_repo: ~/repositories/pihole

  tasks:
    - name: Checkout PiHole repo
      git:
        repo: 'https://github.com/pi-hole/pi-hole.git'
        dest: pihole_repo
        single_branch: true
        version: master
        depth: 1

    - name: Debug print repository content
      shell: 'ls -l {{ pihole_repo }}'

    - name: Execute install script
      shell: 'basic-install.sh'
      args:
        chdir: '{{ pihole_repo }}/automated install'
      become: true
