---
name: Lint

on:
  push:
    branches:
      - '*'
    paths:
      - '**.yml'
  pull_request:
    paths:
      - '**.yml'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code
        run: |
          yamllint .
          ansible-lint
