---
name: Test PiHole Script

on:
  push:
    branches:
      - '*'
    paths:
      - 'pihole/**'
      - '.github/workflows/pihole.yml'
  pull_request:
    paths:
      - 'pihole/**'
      - '.github/workflows/pihole.yml'
  schedule:
    - cron: "0 5 * * 4"

jobs:

  test:
    name: Test PiHole Script
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: pihole
    
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Upgrade pip.
        run: pip3 install --upgrade pip

      - name: Install test dependencies.
        run: sudo pip3 install ansible

      - name: Set up the test environment.
        run: |
          ansible-galaxy install -r requirements.yml
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Test the playbook's syntax.
        run: ansible-playbook main.yml --syntax-check
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Test the playbook.
        run: ansible-playbook -v main.yml
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook main.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        working-directory: ${{ env.PROJECT_DIR }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
